protobuf-c: Export native protoc
configure detects protoc based on some pkgconfig logic which confuses
cross compilation and ends up choosing /usr/bin/protoc causing build
failures when host system has version mismatched protoc installed, it
works ok as long as compatible protoc is installed

Fixes
./protobuf-c/protobuf-c.pb.h:17:2: error: This file was generated by an older version of protoc which is
 ^

Signed-off-by: Khem Raj <raj.khem@gmail.com>